# Generated by Django 5.2 on 2025-04-25 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('match', 'Profile Match'), ('message', 'New Message'), ('system', 'System Notification')], max_length=20, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('related_entity_id', models.IntegerField(blank=True, null=True, verbose_name='Related entity ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
