# Generated by Django 5.2 on 2025-05-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlymissingprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recentlymissingprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentlymissingprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Đang tìm kiếm'), ('closed', 'Đã đóng'), ('found', 'Đã tìm thấy')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='RecentlyMissingProfileImage',
        ),
    ]
