# Generated by Django 5.2 on 2025-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0002_alter_recentlymissingprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facematchresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recentlymissingprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
