# Generated by Django 5.2 on 2025-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0003_alter_facematchresult_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlymissingprofile',
            name='contact_persons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
