# Generated by Django 5.2 on 2025-05-24 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0004_recentlymissingprofile_contact_persons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlymissingprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='RecentlyMissingReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('seeker', 'Người đi tìm'), ('finder', 'Người cung cấp thông tin')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('missing_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contact_persons', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Đang tìm kiếm'), ('closed', 'Đã đóng'), ('found', 'Đã tìm thấy')], default='active', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Missing Report',
                'verbose_name_plural': 'Recently Missing Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPersonMatchResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('face_match_score', models.FloatField()),
                ('llm_confidence', models.CharField(blank=True, choices=[('high', 'Cao'), ('medium', 'Trung bình'), ('low', 'Thấp')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_report1', to='recently_missing.recentlymissingreport')),
                ('report2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_report2', to='recently_missing.recentlymissingreport')),
            ],
            options={
                'verbose_name': 'Missing Person Match Result',
                'verbose_name_plural': 'Missing Person Match Results',
                'unique_together': {('report1', 'report2')},
            },
        ),
        migrations.DeleteModel(
            name='FaceMatchResult',
        ),
        migrations.DeleteModel(
            name='RecentlyMissingProfile',
        ),
    ]
