# Generated by Django 5.2 on 2025-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0005_rename_profile_to_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersonmatchresult',
            name='llm_confidence',
            field=models.CharField(blank=True, choices=[('uncertain', 'Chưa chắc chắn'), ('moderate', 'Có thể trung bình'), ('fairly_confident', 'Trung bình chắc chắn'), ('confident', 'Khá chắc chắn'), ('highly_confident', 'Rất chắc chắn')], max_length=20),
        ),
    ]
