# Generated by Django 5.2 on 2025-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0006_alter_missingpersonmatchresult_llm_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonmatchresult',
            name='llm_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
