# Generated by Django 5.2 on 2025-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_missing', '0007_missingpersonmatchresult_llm_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersonmatchresult',
            name='llm_confidence',
            field=models.CharField(blank=True, choices=[('uncertain', 'Chưa chắc chắn'), ('moderate', 'Có thể trung bình'), ('fairly_confident', 'Trung bình chắc chắn'), ('confident', 'Khá chắc chắn'), ('highly_confident', 'Rất chắc chắn'), ('match', 'Khớp hoàn toàn'), ('partial', 'Khớp một phần'), ('no_match', 'Không khớp')], max_length=20),
        ),
    ]
