# Generated by Django 5.2 on 2025-04-25 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of missing person')),
                ('name_of_father', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's name")),
                ('name_of_mother', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's name")),
                ('born_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year of birth')),
                ('losing_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year of disappearance')),
                ('siblings', models.JSONField(blank=True, help_text='List of siblings as JSON', null=True, verbose_name='Siblings')),
                ('description', models.TextField(verbose_name='Detailed description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('found', 'Found'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Match status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_profile1', to='profiles.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_profile2', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile1', 'profile2')},
            },
        ),
    ]
