# Generated by Django 5.2 on 2025-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='siblings',
            field=models.TextField(blank=True, help_text='List of siblings as plain text', null=True, verbose_name='Siblings'),
        ),
    ]
