# Generated by Django 5.2 on 2025-05-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
