# Generated by Django 5.2 on 2025-05-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilematchsuggestion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['-created_at']},
        ),
    ]
