# Generated by Django 5.2 on 2025-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profileimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={},
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Image URL'),
        ),
    ]
