# Generated by Django 5.2 on 2025-05-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profileimage_options_alter_profileimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilematchsuggestion',
            options={'ordering': ['-match_score']},
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='born_year_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='father_name_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='location_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='losing_year_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='mother_name_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='name_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='siblings_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_source', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_target', to='profiles.profile'),
        ),
    ]
