# Generated by Django 5.2 on 2025-05-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profilematchsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilematchsuggestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='born_year_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='father_name_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='location_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='losing_year_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='match_details',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='match_summary',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='mother_name_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='name_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='siblings_similarity',
        ),
        migrations.RemoveField(
            model_name='profilematchsuggestion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_profile1', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_profile2', to='profiles.profile'),
        ),
    ]
