# Generated by Django 5.2 on 2025-05-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profilematchsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilematchsuggestion',
            options={'ordering': ['-match_score']},
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='differing_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_strength',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='match_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='matching_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilematchsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_source', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profilematchsuggestion',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_as_target', to='profiles.profile'),
        ),
    ]
