# Generated by Django 5.2 on 2025-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profilematchsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
